export const FETCH_MONTHLY_EXPENSE_DETAILS = 'dashboard/FETCH_MONTHLY_EXPENSE_DETAILS';
export const SET_MONTHLY_EXPENSE_DETAILS = 'dashboard/SET_MONTHLY_EXPENSE_DETAILS';
export const ADD_EXPENSE = 'dashboard/ADD_EXPENSE';
export const SET_TOTAL_EXPENSES_FOR_ALL_MONTHS = 'dashboard/SET_TOTAL_EXPENSES_FOR_ALL_MONTHS';
export const SET_TOTAL_AMOUNT_FOR_CURRENT_MONTH = 'dashboard/SET_TOTAL_AMOUNT_FOR_CURRENT_MONTH';
