export const FETCH_MONTHLY_EXPENSE_DETAILS = 'FETCH_MONTHLY_EXPENSE_DETAILS';
export const SET_MONTHLY_EXPENSE_DETAILS = 'SET_MONTHLY_EXPENSE_DETAILS';
export const ADD_EXPENSE = 'ADD_EXPENSE';
export const SET_TOTAL_EXPENSES_FOR_ALL_MONTHS = 'SET_TOTAL_EXPENSES_FOR_ALL_MONTHS';
export const SET_TOTAL_AMOUNT_FOR_CURRENT_MONTH = 'SET_TOTAL_AMOUNT_FOR_CURRENT_MONTH';
export const SET_CATEGORY_WISE_EXPENSE_FOR_A_MONTH = 'SET_CATEGORY_WISE_EXPENSE_FOR_A_MONTH';
export const SET_CATEGORY_WISE_EXPENSE_FOR_ALL_MONTHS = 'SET_CATEGORY_WISE_EXPENSE_FOR_ALL_MONTHS';
